name: Build Motorola Nicklaus ROM

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Cleanup
        uses: rokibhasansagar/slimhub_actions@main

      - name: Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 12
        
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo docker pull mlmgames/aosp_7.1

      - name: Run build in Docker container
        run: |
          sudo docker run --rm \
            -v ${{ github.workspace }}:/github/workspace \
            -w /github/workspace \
            mlmgames/aosp_7.1 \
            /bin/bash -c "
              # Install repo
              mkdir -p ~/bin
              curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
              chmod a+x ~/bin/repo
              export PATH=\$PATH:~/bin
              # Initialize Repo with minimal depth
              mkdir ~/workdir
              cd ~/workdir
              repo init --depth=1 -u https://github.com/LineageOS/android.git -b cm-14.1
              # Sync sources with minimal options
              repo sync \
                --current-branch \
                --no-tags \
                --no-clone-bundle \
                --optimized-fetch \
                --prune \
                --force-sync \
                -j$(nproc) \
                --depth=1
              # Clone device trees with minimal depth
              git clone --depth=1 https://github.com/mlm-games/android_device_motorola_nicklaus -b cm-14.1 device/motorola/nicklaus
              git clone --depth=1 https://github.com/LineageOS-MediaTek/android_device_mediatek_mt6737-common -b cm-14.1 device/mediatek/mt6737-common
              git clone --depth=1 https://github.com/LineageOS-MediaTek/proprietary_vendor_motorola -b cm-14.1 vendor/motorola
              git clone --depth=1 https://github.com/Klozz/android_kernel_motorola_nicklaus kernel/motorola/nicklaus
              # Set build flags for optimization
              export USE_DEX2OAT_DEBUG=false
              export WITH_DEXPREOPT=false
              export WITH_DEXPREOPT_BOOT_IMG_ONLY=false
              export DISABLE_DEXPREOPT=true
              export PRODUCT_MINIMIZE_JAVA_DEBUG_INFO=true
              export TEMPORARY_DISABLE_PATH_RESTRICTIONS=true
              # Additional memory optimizations
              export JACK_SERVER_VM_ARGUMENTS='-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx4g'
              export ANDROID_JACK_VM_ARGS='-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx4g'
              export _JAVA_OPTIONS='-Xmx4g'
              # Start building
              cd ~/workdir  # Make sure we're in the correct directory
              source build/envsetup.sh
              breakfast nicklaus
              make -j$(nproc) bacon | tee build.log
            "
      
      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: nicklaus-build
          path: |
            ~/workdir/out/target/product/nicklaus/*.zip
            ~/workdir/out/target/product/nicklaus/*.md5sum
            ~/workdir/build.log
